const Router = require('express')
const router = new Router()
const eventsRouter = require('./eventsRouter')
const newsletterRouter = require('./newsletterRouter')
const partnersRouter = require('./partnersRouter')
const photoRouter = require('./photoRouter')
const reservationRouter = require('./reservationRouter')
const reviewsRouter = require('./reviewsRouter')
const teachersRouter = require('./teachersRouter')
const socialRouter = require('./socialRouter')
const statisticsRouter = require('./statisticsRouter')
const shiftsRouter = require('./shiftsRouter')
const shiftRouter = require('./shiftRouter')
const typeRouter = require('./typeRouter')
const userRouter = require('./userRouter')

router.use('/events', eventsRouter)
router.use('/newsletter', newsletterRouter)
router.use('/partners', partnersRouter)
router.use('/photo', photoRouter)
router.use('/reservation', reservationRouter)
router.use('/reviews', reviewsRouter)
router.use('/teachers', teachersRouter)
router.use('/social', socialRouter)
router.use('/statistics', statisticsRouter)
router.use('/shifts', shiftsRouter)
router.use('/shift', shiftRouter)
router.use('/type', typeRouter)
router.use('/user', userRouter)


module.exports = router