export const PUBLIC_ROUTE = '/'
export const LOGIN_ROUTE = '/join'
export const ADMIN_ROUTE = '/admin'
export const EVENT_ROUTE = '/event'
export const NEWSLETTER_ROUTE = '/newsletter'
export const PARTNERS_ROUTE = '/partners'
export const PHOTO_ROUTE = '/photo'
export const RESERVATION_ROUTE = '/reservation'
export const REVIEWS_ROUTE = '/reviews'

export const SHIFT_ROUTE = '/shift'
export const SHIFTS_ROUTE = '/shifts'
export const SOCIAL_ROUTE = '/social'
export const STATISTICS_ROUTE = '/statistics'
export const TEACHERS_ROUTE = '/teachers'
export const TYPE_ROUTE = '/type'

