const Router = require('express')
const router = new Router()
const user = require('./userRouter')
const newsletter = require('./newsletterRouter')
const events = require('./eventsRouter')
const partners = require('./partnersRouter')
const photo = require('./photoRouter')
const reservation = require('./reservationRouter')
const teachers = require('./teachersRouter')
const reviews = require('./reviewsRouter')
const type = require('./typeRouter')
const program = require('./programRouter')
const shifts = require('./shiftsRouter')
const news = require('./newsRouter')
const offers = require('./offersRouter')
const daySchedule = require('./dayScheduleRouter')
const questions = require('./questionsRouter')
const schedule = require('./scheduleRouter')
const sections = require('./sectionsRouter')

router.use('/user', user)
router.use('/newsletter', newsletter)
router.use('/news', news)
router.use('/events', events)
router.use('/partners', partners)
router.use('/photo', photo)
router.use('/reservation', reservation)
router.use('/teachers', teachers)
router.use('/reviews', reviews)
router.use('/type', type)
router.use('/shifts', shifts)
router.use('/program', program)
router.use('/offers', offers)
router.use('/daySchedule', daySchedule)
router.use('/questions', questions)
router.use('/schedule', schedule)
router.use('/sections', sections)

module.exports = router